{% set name = "napari-microscope" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-microscope-{{ version }}.tar.gz
  sha256: 65efe52ed6ac1ee312256d87ec8e3945738cd93449f0a55c6bf75f48cc232fe1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - microscope
    - napari-plugin-engine
    - pyro4
    - python >={{ python_min }}

test:
  imports:
    - napari_microscope
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-microscope/
  summary: Napari plugin for Microscope.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
